#!/bin/bash
servers=$(cat servers.txt)
for i in $servers; do
  ping -c 1 $1 >> /dev/null 2>&1
  if [ $? -ne 0 ]; then
    echo "Sending out an outage email."
    echo "$i is unreacheable." | mail -s "$i Outage" [your email]
  fi
done
